[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set laststatus=2
  set showmode
  set showcmd
  set ruler
'''

[[plugins]]
repo = '4513ECHO/vim-colors-hatsunemiku'
hook_add = '''
  autocmd COlorScheme * highlight Normal ctermbg=none
  autocmd COlorScheme * highlight LineNr ctermbg=none
  autocmd COlorScheme * highlight CursorLine ctermbg=none cterm=none
  autocmd COlorScheme * highlight CursorLineNr ctermbg=none cterm=underline
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

