
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_i = 1

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufEnter'

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
on_event = 'BufEnter'
hook_source = '''
lua << EOF
vim.opt.list = true
vim.opt.listchars:append "eol:↴"

require("indent_blankline").setup {
  show_current_context = true,
  show_current_context_start = true,
}
EOF
'''

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = 'BufEnter'
hook_source = '''
lua << EOF
require('nvim-autopairs').setup()
EOF
'''

[[plugins]]
repo = 'j-hui/fidget.nvim'
on_event = 'BufEnter'
hook_source = '''
lua << EOF
require('fidget').setup()
EOF
'''

[[plugins]]
repo = 'Maan2003/lsp_lines.nvim'
on_event = 'BufEnter'
hook_source = '''
lua << EOF
require('lsp_lines').setup()
EOF
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
on_i = 1
hook_source = '''
call coil398#init#coc#hook_source()
'''
